maintainer       "Keno Fischer"
maintainer_email "kfischer@college.harvard.edu"
license          "MIT"
description      "Installs the gfortran package"
version          "0.1"
depends "build-essential"
